
@api = http://localhost:3000/
@token = 

###
POST {{api}}auth/signup
Content-Type: application/json

{
    "name": "Jhon",
    "lastname": "Fix",
    "email": "jhon@gmail.com",
    "password": "12345"
}
###

POST {{api}}auth/signin
Content-Type: application/json

{
    "email": "jhon@gmail.com",
    "password": "12345"
}
###

POST {{api}}auth/check-token
Content-Type: application/json

{
    "token": "{{token}}"
}