
@api = http://localhost:3000/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxNjYxNDY2MzgzNjYxLCJpYXQiOjE2NjE0NjYzODMsImV4cCI6MTY2MTQ2OTk4M30.B_Xynmq9w47ltuVJV5ZLaXBYUnUMyQyiuL7mqpQMrwo

###
POST {{api}}auth/signup
Content-Type: application/json

{
    "name": "Jhon",
    "lastname": "Fix",
    "email": "jhon@gmail.com",
    "password": "12345"
}
###

POST {{api}}auth/signin
Content-Type: application/json

{
    "email": "ejcastelg@gmail.com",
    "password": "12345"
}
###

POST {{api}}auth/check-token
Content-Type: application/json

{
    "token": "{{token}}"
}