@api = http://localhost:3000/
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJkYXRhIjoxNjYxNDY2MzgzNjYxLCJpYXQiOjE2NjE0NjYzODMsImV4cCI6MTY2MTQ2OTk4M30.B_Xynmq9w47ltuVJV5ZLaXBYUnUMyQyiuL7mqpQMrwo

###
GET {{api}}notes/14
Content-Type: application/application/application/json
token: {{token}}
###

POST {{api}}notes
Content-Type:  application/json
token: {{token}}

{
    "title": "Programar",
    "description": "terminar Interfaz",
    "important": 1,
    "created_user": 9
}
###

PUT {{api}}notes/4
Content-Type:  application/json
token: {{token}}

{
    "title": "Jugar",
    "description": "Jugar Portal knight",
    "important": 4
}
###
DELETE {{api}}notes/6
token: {{token}}