@api = http://localhost:3000/
@token = 

###
GET {{api}}notes/1
Content-Type: application/application/application/json
token: {{token}}
###

POST {{api}}notes
Content-Type:  application/json
token: {{token}}

{
    "title": "Front End",
    "description": "Interfaz",
    "important": 4,
    "created_user": 3
}
###

PUT {{api}}notes/4
Content-Type:  application/json
token: {{token}}

{
    "title": "Jugar",
    "description": "Jugar Portal knight",
    "important": 4
}
###
DELETE {{api}}notes/6
token: {{token}}